name: Deploy Backend to DigitalOcean
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Docker image
      run: docker build -t avtoforum-backend .
      
    - name: Save Docker image
      run: docker save avtoforum-backend > avtoforum-backend.tar
      
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DO_HOST_BACKEND }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        source: "avtoforum-backend.tar"
        target: "/root/"
        
    - name: Deploy on server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DO_HOST_BACKEND }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        script: |
          cd /root
          docker load < avtoforum-backend.tar
          docker stop avtoforum-backend || true
          docker rm avtoforum-backend || true
          docker run -d --name avtoforum-backend -p 8080:8080 avtoforum-backend
